spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: JwtAuthenticationFilter

server:
  port: 8080

jwt:
  secret: "your-jwt-secret-key-here"
  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.chatapp.apigateway: DEBUG