spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: JwtAuthenticationFilter

server:
  port: 8080