spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chat_aggregate
    username: chat
    password: chat
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: false
    placeholders:
      table-prefix: auth_
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    table: flyway_schema_history_auth

server:
  port: 8081