server:
  port: 8761

spring:
  application:
    name: discovery-service
  security:
    user:
      name: admin
      password: admin

# Eureka Server Configuration
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false    # This is a server, doesn't register with itself
    fetch-registry: false          # This is a server, doesn't need to fetch registry
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: true     # Prevents removal of services during network issues
    renewal-percent-threshold: 0.85    # Percentage of renewals needed to avoid eviction
    eviction-interval-timer-in-ms: 60000  # How often to check for expired services
    response-cache-update-interval-ms: 30000  # How often to update the response cache

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
    org.springframework.cloud.eureka: DEBUG